name: package examples

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Package example projects as zips
        run: ./scripts/package_examples.sh

      - name: Upload assets to this release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.zip
            docs/*.json

  jitpack-test:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger JitPack build
        run: |
          curl -s "https://jitpack.io/com/github/captainsoccer/BasicMotor/${GITHUB_REF_NAME}/build.log" \
            -o jitpack-build.log
          echo "JitPack log saved to jitpack-build.log"
          head -n 50 jitpack-build.log
